# Generated by Django 5.1.1 on 2024-10-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('Id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('adminNom', models.CharField(max_length=255)),
                ('adminPrenom', models.CharField(max_length=255)),
                ('adminEmail', models.EmailField(max_length=255)),
                ('adminTel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructures',
            fields=[
                ('Id_Infratrs', models.AutoField(primary_key=True, serialize=False)),
                ('infratsNom', models.CharField(max_length=255)),
                ('infratsLocalition', models.CharField(max_length=255)),
                ('infratsDescrip', models.CharField(max_length=300)),
                ('infratsEtat', models.CharField(max_length=30)),
                ('infratsDateEnrg', models.DateField()),
                ('Id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestionInfrastructure.administration')),
            ],
        ),
        migrations.CreateModel(
            name='Interventions',
            fields=[
                ('Id_Intertns', models.AutoField(primary_key=True, serialize=False)),
                ('intertnsDate', models.DateField()),
                ('Id_Infratrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestionInfrastructure.infrastructures')),
            ],
        ),
    ]
