# Generated by Django 5.1.1 on 2024-10-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionInfrastructure', '0002_administration_adminmotpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructures',
            name='infratsDateEnrg',
            field=models.DateField(auto_now_add=True),
        ),
    ]
