# Generated by Django 5.1.1 on 2024-10-03 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionInfrastructure', '0003_alter_infrastructures_infratsdateenrg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructures',
            name='Id_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppGestionInfrastructure.administration'),
        ),
    ]
